package org.bcholmes.cartographersvg;

public enum InfoBlockType {

	HEADER, UNUSED_1, VIEWS, LAYERS, GRIDS, PRINTER_SETTINGS, LINE_STYLES, 
	FILL_STYLES, NAMED_VIEWS, COLOR_MAP_DATA, UNUSED_10, UNUSED_11, UNUSED_12,
	UNUSED_13, UNUSED_14, UNUSED_15, DIMENSION_STYLES, FONTS;
}
